apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: training-app
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://training-app.local/api"